version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: lemp_mysql
    volumes:
      - ./www/dbdata:/usr/data
      - ./mysql/conf.d:/etc/mysql/conf.d/
      - ./mysql/mysql.conf.d:/etc/mysql/mysql.conf.d/
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
  php:
    build: ./phpdocker-php70
    container_name: lemp_php
    volumes:
      - ./www:/var/www
    depends_on:
      - mysql
  nginx:
    image: evild/alpine-nginx:1.9.15-openssl
    container_name: lemp_nginx
    links:
      - php
    volumes:
      - ./www:/var/www/:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
      - 443:443 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lemp_phpmyadmin
    links:
      - mysql
    ports:
      - 8183:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret